######################################################################
# Automatically generated by qmake (3.0) ? 8? 17 02:49:42 2019
######################################################################

TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt
LIBS += -lpcap

SOURCES += \
        main.cpp

HEADERS += \
    headers.h
